# Generated by Django 2.1.7 on 2019-04-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='quest',
            field=models.TextField(null=True),
        ),
    ]
