# Generated by Django 2.1.7 on 2019-04-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190406_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
