# Generated by Django 2.1 on 2020-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200911_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
